### ISSUE TITLE
Not launching on Windows 11

### ISSUE THREAD

**Issue by K7L393** [SaifAqqad/corsair_battery_level#5]
I'm trying to run the executable but it does not open, no sign of it running at all.

OS Name	Microsoft Windows 11 Pro
Version	10.0.22621 Build 22621

**Comment by K7L393** [comment]
I was successfully able to build it and run it in node.
but the EXE does not run.

**Comment by SaifAqqad** [comment]
I published a new build [v2.0.3](https://github.com/SaifAqqad/corsair_battery_level/releases/tag/2.0.3) that should fix this issue
